### ISSUE TITLE
API: blocchi di codice e katex non ben formattati

### ISSUE THREAD

**Issue by etabeta1** [titilda/appunti#12]
Compaiono blocchi di codice formattati come katex e non come codice.

I blocchi sono i seguenti:
- Insertion sort

Compaiono blocchi di katex non ben formattati.

I blocchi sono i seguenti:
- Tabelle hash: esempio del metodo della divizione
- Tabelle hash: esempio del metodo della moltiplicazione

Compaiono blocchi di katex segnati come blocchi anche se dovrebbero essere inline.

I blocchi sono i seguenti:
- PDAND: definizione di delta
- Linguaggio generato: esempio
- Complessità del calcolo: complessità spaziale
- Complessità del calcolo: somma delle quantità massime utilizzate
- Complessità spaziale: transitività
- Complessità spaziale: riflessività
- Macchina RAM
- Macchina RAM: ricerca binaria
- Mergesort: equazione di ricorrenza (entrambe le volte)
- Teorema dell'esperto
- Teorema dell'esperto merge sort
- Ricorrenze di ordine costante
- Ipotesi dell'hashing uniforme semplice
- Metodo della moltiplicazione: valore di $A$
- Metodo della moltiplicazione: inverso sezione aurea
- Indirizzamento aperto: funzione ausiliaria
- Argomenti avanzati: peso cammino
- Argomenti avanzati: peso cammino minimo

**Comment by ilgrandedumbo** [comment]
$$
\delta (u,v)=\begin{cases}
    min\{w(p):u \to^p v\}\ se\ esiste\ cammino\ p\ da\ u\ a\ v
    \\
    \infty\ altrimenti
\end{cases}
$$

Non trovo un modo per fare la stessa visualizzazione grafica senza usare un blocco
