### ISSUE TITLE
Aggiungere stile per blocchi di codice

### ISSUE THREAD

**Issue by etabeta1** [titilda/appunti#4]
~Per ora non è necessario ma sarà necessario quando gli appunti di misure verranno pubblicati~

A quanto pare non è necessario, però i blocchi di codice non vanno a capo in automatico se la riga è troppo lunga, bisogna aggiustare.

**Comment by TheManchineel** [comment]
Sarebbe figo (anche se non so quanto sia semplice) integrare in qualche modo Highlight.js in modo da evidenziare anche la sintassi. Discussione rilevante? https://github.com/jgm/pandoc/issues/3353

**Comment by etabeta1** [comment]
Non è una cattiva idea, magari un giorno vediamo di implementarlo (se non conflitta con i grafici mermaid, che anche quelli sono blocchi di codice)

**Comment by etabeta1** [comment]
Custom pandoc filter? https://pandoc.org/filters.html
Facciamo che tutti i grafici mermaid vengono ignorati mentre tutti gli altri blocchi di codice vengono messi in un `<pre><code class="...">...</code></pre>`?

**Comment by etabeta1** [comment]
> integrare in qualche modo Highlight.js

A quanto pare non è necessario (almeno per Java).
Il problema è che righe troppo lunghe non vanno a capo, va sistemato.

**Comment by etabeta1** [comment]
Sistemato con bootstrap
