### ISSUE TITLE
Improve printing support ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by TheManchineel** [titilda/appunti#5]
As things stand, printing experience 🖨️ is rather mediocre on this repo 😥 Please improve the CSS so that irrelevant items are excluded from the page, no margins constrain the print area of the page and maybe even use print-friendly 🌱 colors to save the environment! 😇

**Comment by etabeta1** [comment]
Fixed in [89c8d14](https://github.com/titilda/appunti/commit/89c8d14a407763be81609c8189bbf4e7d2f881ce)

**Comment by TheManchineel** [comment]
> Fixed in [89c8d14](https://github.com/titilda/appunti/commit/89c8d14a407763be81609c8189bbf4e7d2f881ce)

THANKS!!!! 😊😘😍🥰😁🙏😀☺️🙏🙏😊😘😊🥰☺️
