### ISSUE TITLE
Action non interrotta quando avviene un push durante l'esecuzione

### ISSUE THREAD

**Issue by etabeta1** [titilda/appunti#7]
E' possibile fare in modo che, se avviene un push durante l'esecuzione dell'action per la pubblicazione, questa venga interrotta e parta subito quella nuova? Non dovrebbe rompersi nulla se succede.

**Comment by TheManchineel** [comment]
L'esecutore delle GHA è totalmente arbitrario, quindi non c'è un modo nativo per farlo. Andrebbe scritta (o usata) un'azione custom che usa l'API di GitHub per annullare l'esecuzione di altre actions in corso in caso di commit, come ad esempio questa: https://github.com/marketplace/actions/cancel-workflow-action

**Comment by etabeta1** [comment]
In `gh-pages.yml` la riga 21 non è esattamente quello che ci serve?

**Comment by TheManchineel** [comment]
@etabeta1 Mi sa che hai ragione. Dovrebbe funzionare adesso, se ci fossero problemi in connessione a questo cambiamento si può aprire una nuova issue. Grazie!
